# Don't change this! Version used to track needed updates.
version = 0
enableParticleCulling = true
particleRenderDistance = 5
particleCullingBlocklist = [  ]
cullParticlesInUnloadedChunks = true
allowUsingBlendedRenderType = true
spellParticlesUseBlendedRenderType = true
glowingLavaDrops = true
fluidDropsEvaporate = true
fluidDropsEvaporationVolume = 0.25
dropLandInFluidRipples = true
dropLandSoundVolume = 1.0
lavaSparkSmoke = true
sparksScale = 1.0
poppingHearts = true
poppingBubbles = true
poppingBubblesVolume = 0.2
glowingEnchantmentParticles = true
translucentEnchantmentParticles = true
disableRandomizedShading = true
potionParticleAlpha = 0.7
potionParticleAlphaNearPlayer = 0.2
leavesLandOnGround = true
leavesLandOnWater = true
leavesLandingOnWaterRipples = true
leavesLandingOnWaterKeepMomentum = true
fallenLeavesLifeTime = 60
rainIncreasesLeavesMovementSpeed = true
fireOverlayHeight = -0.19705883
fireOverlayAlpha = 0.8006536
fireOverlayAlphaWithFireResistance = 0.24509804
mobSkullShaders = false
nightVisionFading = true
nightVisionFadingTime = 200
enableEasterEggs = true