
[misc]
	#Signed Album item will have an enchantment glint.
	signed_album_glint = true
	#Mundane, Awkward and Thick potions will have their color changed slightly, so it's easier to tell them apart. Default: true
	different_developing_potions_colors = true
	#Generate photographs and film rolls in loot chests. Default: true
	loot_chests = true
	#Convert old photograph IDs to the new system (1.7 -> 1.9 update). Makes old photos visible, but results may be undesirable (missing pixels, different colors, etc).
	#Default: true
	datafix_old_ids = true

