# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
maxParticlesPerSheet = 16384
particleRenderDistanceMultiplier = 1.0
asynchronousTicking = true
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
turnOffPotionParticlesV2 = [
    "SELF"
]

[byTypeReductions]
"minecraft:damage_indicator" = 0.0
"minecraft:smoke" = 0.5
"subtle_effects:sculk_dust" = 0.24509803921568626
"subtle_effects:firefly_emitter" = 0.0
"subtle_effects:firefly" = 0.0