onCull = true
MaxEntityEntities = 128
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = true
blackListedEntities = []
whiteListedEntities = ["minecraft:player"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 137.059
onGui = false
GuiRXTX = false
GuiFPS = false
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = true
MaxParticleDistance = 129
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "EMPTY"
MinDistance = 8
EntityDistance = 128
TickPerformance = true
ParticlePerformance = false
EntityPerformance = true
EntityViewDebug = false
ParticleCountLimit = 16384
BlockBreakParticle = true
AsyncCompute = true
