
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				creeper = true
				skeleton = true
				item = true
				cod = true
				spider = true
				enderman = true
				zombie = true
				glow_squid = true
				zombie_villager = true
				squid = true
				dolphin = true
				bat = true
				pig = true
				fox = true
				parrot = true
				turtle = true
				chicken = true
				sheep = true
				bee = true
				tropical_fish = true
				wolf = true
				painting = true
				villager = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				arrow = true
				axolotl = true
				blaze = true
				block_display = true
				boat = true
				camel = true
				cat = true
				cave_spider = true
				chest_boat = true
				chest_minecart = true
				command_block_minecart = true
				cow = true
				donkey = true
				dragon_fireball = true
				drowned = true
				egg = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				ender_pearl = true
				endermite = true
				evoker = true
				evoker_fangs = true
				experience_bottle = true
				experience_orb = true
				eye_of_ender = true
				falling_block = true
				firework_rocket = true
				frog = true
				furnace_minecart = true
				ghast = true
				giant = true
				glow_item_frame = true
				goat = true
				guardian = true
				hoglin = true
				hopper_minecart = true
				horse = true
				husk = true
				illusioner = true
				interaction = true
				iron_golem = true
				item_display = true
				item_frame = true
				fireball = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				mooshroom = true
				mule = true
				ocelot = true
				panda = true
				phantom = true
				piglin = true
				piglin_brute = true
				pillager = true
				polar_bear = true
				potion = true
				pufferfish = true
				rabbit = true
				ravager = true
				salmon = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton_horse = true
				slime = true
				small_fireball = true
				sniffer = true
				snow_golem = true
				snowball = true
				spawner_minecart = true
				spectral_arrow = true
				stray = true
				strider = true
				tadpole = true
				text_display = true
				tnt = true
				tnt_minecart = true
				trader_llama = true
				trident = true
				vex = true
				vindicator = true
				wandering_trader = true
				warden = true
				witch = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				zoglin = true
				zombie_horse = true
				zombified_piglin = true
				fishing_bobber = true

			[light_sources.settings.entities.alexsmobs]
				lobster = true
				leafcutter_ant = true
				cockroach = true
				cachalot_whale = true
				seagull = true
				seal = true
				blue_jay = true
				crow = true
				gorilla = true
				raccoon = true
				grizzly_bear = true
				toucan = true
				cachalot_echo = true
				capuchin_monkey = true
				tasmanian_devil = true
				kangaroo = true
				gazelle = true
				rhinoceros = true
				emu = true
				maned_wolf = true
				crocodile = true
				fly = true
				centipede_head = true
				centipede_body = true
				centipede_tail = true
				elephant = true
				flying_fish = true
				giant_squid = true
				frilled_shark = true
				blobfish = true
				mantis_shrimp = true
				murmur = true
				murmur_head = true
				catfish = true
				alligator_snapping_turtle = true
				sugar_glider = true
				bald_eagle = true
				bison = true

			[light_sources.settings.entities.tide]
				tuna = true
				barracuda = true
				mackerel = true
				bluegill = true
				pike = true
				ocean_perch = true
				guppy = true
				yellow_perch = true
				bass = true
				mint_carp = true
				catfish = true
				trout = true
				sailfish = true
				fishing_bobber = true

			[light_sources.settings.entities.naturalist]
				coral_snake = true
				robin = true
				lizard = true
				snail = true
				butterfly = true
				snake = true
				boar = true
				giraffe = true
				bass = true
				elephant = true
				cardinal = true
				firefly = true
				deer = true
				catfish = true
				dragonfly = true
				hippo = true
				duck = true
				bluejay = true
				alligator = true
				tortoise = true
				canary = true
				lizard_tail = true
				finch = true

			[light_sources.settings.entities.quark]
				toretoise = true
				stoneling = true
				forgotten = true
				glass_frame = true

			[light_sources.settings.entities.born_in_chaos_v1]
				baby_spider = true
				zombie_bruiser = true
				skeleton_thrasher = true
				restless_spirit = true
				siamese_skeletons = true
				baby_skeleton = true
				zombie_lumberjack = true
				swarmer = true
				phantom_creeper = true
				skeleton_demoman = true
				dread_hound = true
				decaying_zombie = true
				spirit_guide = true
				door_knight = true
				decrepit_skeleton = true
				fallen_chaos_knight = true
				corpse_fly = true
				mother_spider = true
				spirit_guide_assistant = true
				spiritof_chaos = true
				staffof_blindness_projectile = true
				dire_hound_leader = true
				siamese_skeletonsright = true
				siamese_skeletonsleft = true
				barrel_zombie = true
				glutton_fish = true
				zombie_fisherman = true
				bloody_gadfly = true
				maggot = true
				pumpkin_spirit = true
				seared_spirit_not_despawn = true
				thornshell_crab = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.ars_nouveau]
				whirlisprig = true
				starbuncle = true
				drygmy = true
				spell_proj = true
				gift_starby = true

			[light_sources.settings.entities.crittersandcompanions]
				sea_bunny = true
				otter = true
				dragonfly = true
				leaf_insect = true
				dumbo_octopus = true
				jumping_spider = true

			[light_sources.settings.entities.rediscovered]
				fish = true
				rana = true

			[light_sources.settings.entities.mcdw]
				summoned_bee = true

			[light_sources.settings.entities.mythicmetals]
				banglum_tnt_minecart = true
				banglum_tnt = true
				banglum_nuke = true
				star_platinum_arrow = true
				runite_arrow = true

			[light_sources.settings.entities.majruszsdifficulty]
				cerberus = true
				creeperling = true
				cursed_armor = true
				giant = true
				illusioner = true
				tank = true

			[light_sources.settings.entities.exposure]
				photograph = true
				photograph_frame = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.botania]
				mana_burst = true
				pixie = true
				flame_ring = true
				vine_ball = true
				doppleganger = true
				magic_landmine = true
				spark = true
				thrown_item = true
				magic_missile = true
				thorn_chakram = true
				corporea_spark = true
				ender_air_bottle = true
				pool_minecart = true
				pink_wither = true
				player_mover = true
				mana_storm = true
				babylon_weapon = true
				falling_star = true
				ender_air = true

			[light_sources.settings.entities.enhancedai]
				thrown_web = true
				fishing_hook = true

			[light_sources.settings.entities.the_bumblezone]
				variant_bee = true
				honey_slime = true
				beehemoth = true
				bee_queen = true
				rootmin = true
				sentry_watcher = true
				pollen_puff = true
				dirt_pellet = true
				thrown_stinger_spear = true
				bee_stinger = true
				honey_crystal_shard = true
				electric_ring_entity = true
				purple_spike_entity = true
				cosmic_crystal_entity = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.confluence]
				bee_projectile = true
				star_cloak = true
				step_stool = true

			[light_sources.settings.entities.mutantmonsters]
				creeper_minion = true
				mutant_creeper = true
				mutant_enderman = true
				mutant_skeleton = true
				mutant_snow_golem = true
				mutant_zombie = true
				spider_pig = true
				body_part = true
				creeper_minion_egg = true
				endersoul_clone = true
				endersoul_fragment = true
				throwable_block = true
				mutant_arrow = true
				skull_spirit = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.phantasm]
				crystie = true
				behemoth = true
				choral_arrow = true

			[light_sources.settings.entities.galosphere]
				silver_bomb = true
				sparkle = true
				spectre = true
				glow_flare = true
				spectre_flare = true
				specterpillar = true
				spectator_vision = true
				berserker = true
				preserved = true
				pink_salt_pillar = true
				pink_salt_shard = true

			[light_sources.settings.entities.zombieawareness]
				scent = true

			[light_sources.settings.entities.spelunkers_charm]
				tremor_handler = true
				sound_entity = true
				projectile_rock_projectile = true
				projectile_deepslate_rock_projectile = true
				projectile_dripstone_rock_projectile = true
				projectile_basalt_rock_projectile = true

			[light_sources.settings.entities.cataclysm]
				ender_golem = true
				ender_guardian = true
				old_netherite_monstrosity = true
				netherite_monstrosity = true
				netherite_ministrosity = true
				lava_bomb = true
				flare_bomb = true
				flame_jet = true
				lightning_storm = true
				nameless_sorcerer = true
				ignis = true
				ender_guardian_bullet = true
				void_rune = true
				abyss_mine = true
				endermaptera = true
				deepling = true
				deepling_brute = true
				deepling_angler = true
				deepling_priest = true
				deepling_warlock = true
				abyss_mark = true
				lionfish = true
				coral_golem = true
				coralssus = true
				ignited_revenant = true
				ignited_berserker = true
				the_harbinger = true
				the_watcher = true
				the_prowler = true
				the_leviathan = true
				the_baby_leviathan = true
				void_scatter_arrow = true
				poison_dart = true
				phantom_arrow = true
				phantom_halberd = true
				void_shard = true
				blazing_bone = true
				lionfish_spike = true
				coral_spear = true

			[light_sources.settings.entities.ecologics]
				squirrel = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.upgrade_aquatic]
				nautilus = true
				perch = true

			[light_sources.settings.entities.wither_spawn_animation]
				animated_altar_z = true

			[light_sources.settings.entities.aether]
				blue_swet = true
				phyg = true
				aerbunny = true
				flying_cow = true
				zephyr = true
				moa = true
				sheepuff = true
				cockatrice = true
				golden_swet = true
				whirlwind = true
				aechor_plant = true
				slider = true
				aerwhale = true

			[light_sources.settings.entities.aether_redux]
				vanilla_swet = true

			[light_sources.settings.entities.tiab]
				time_accelerator_entity_type = true

