#Whether Obscure Tooltips should be active at all.
enabled = true
#The margin (in pixels) between the tooltip frame and its content.
#Range: 0 ~ 16
contentMargin = 3
#List of item IDs that should be ignored by Obscure Tooltips.
ignoredItems = ["quality_equipment:reforge_gui_button"]

[AutoWrapping]
	#Whether Obscure Tooltips should wrap lines in tooltips.
	autoWrappingEnabled = true

[Scrolling]
	#How fast the tooltip scrolls when using the mouse wheel.
	#Range: 1 ~ 64
	scrollSpeed = 5
	#Extra spacing (in pixels) above and below tooltip when scrolling is enabled.
	#Range: 0 ~ 64
	scrollMargin = 10
	#Whether long tooltips should become scrollable when they exceed the screen height.
	scrollEnabled = true

[ArmorPreview]
	#Whether Obscure Tooltips should display 3D armor previews.
	armorPreviewEnabled = true
	#List of item IDs that should always display a 3D armor preview.
	armorPreviewWhitelist = []
	#List of item IDs that should never display a 3D armor preview.
	armorPreviewBlacklist = []

[ToolPreview]
	#Whether Obscure Tooltips should display 3D tool/weapon previews.
	toolPreviewEnabled = false
	#List of item IDs that should always display a 3D tool/weapon preview.
	toolPreviewWhitelist = ["minecraft:trident", "minecraft:bow", "minecraft:crossbow"]
	#List of item IDs that should never display a 3D tool/weapon preview.
	toolPreviewBlacklist = []

